name: Auto Assign
on: pull_request_target

jobs:
  add-assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.6
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
