name: Auto Assign
on: pull_request

jobs:
  add-assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
